name:                Installer
version:             0.1.0.0
github:              "githubuser/Installer"
license:             BSD-3-Clause
author:              "ruzen42"
maintainer:          "malledeferlive@gmail.com"
copyright:           "2025 Jarolav Mihajlenko"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            Installer for NurOS Linux 
category:            System

description:         Please see the README on GitHub at <https://github.com/NurOS-Linux/NurOS-Start#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Installer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Installer

tests:
  Installer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Installer
